// Generated by https://quicktype.io

export interface Product {
  id?: string;
  title: string;
  price: number;
  description: string;
  category: Category;
  image: string;
  rating: Rating;
}

type Category = "electronics" | "jewelery" | "men's clothing" | "women's clothing" | "";

interface Rating {
  rate: number;
  count: number;
}
