// Generated by https://quicktype.io

export interface Product {
  id?: string;
  title: string;
  price: number;
  description: string;
  category: Category;
  image: string;
}

type Category = "electronics" | "jewelery" | "men's clothing" | "women's clothing" | "";
